---
version: '3.1'

services:
  aragast:
    image: aragast/netology:latest
    build: .
    container_name: aragast
    privileged: true
    working_dir: /opt/vector-role
    volumes:
      - ./:/opt/vector-role
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
    command: /sbin/init
