---
dependency:
  name: galaxy
  enabled: false
driver:
  name: podman
lint: |
  ansible-lint
  yamllint .
platforms:
  - name: centos_7
    image: pycontribs/centos:7
    command: /usr/sbin/init
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible